; Dragon Warrior IV (USA) - lossless, bank-oriented disassembly baseline
; The exact NES 2.0 header is preserved because metadata summaries disagree on mirroring.

    db $4E,$45,$53,$1A,$20,$00,$12,$08,$00,$00,$70,$07,$00,$00,$00,$01

    include "src/constants/hardware.inc"
    include "src/constants/ram.inc"

    include "src/banks/bank_00.asm"
    include "src/banks/bank_01.asm"
    include "src/banks/bank_02.asm"
    include "src/banks/bank_03.asm"
    include "src/banks/bank_04.asm"
    include "src/banks/bank_05.asm"
    include "src/banks/bank_06.asm"
    include "src/banks/bank_07.asm"
    include "src/banks/bank_08.asm"
    include "src/banks/bank_09.asm"
    include "src/banks/bank_0A.asm"
    include "src/banks/bank_0B.asm"
    include "src/banks/bank_0C.asm"
    include "src/banks/bank_0D.asm"
    include "src/banks/bank_0E.asm"
    include "src/banks/bank_0F.asm"
    include "src/banks/bank_10.asm"
    include "src/banks/bank_11.asm"
    include "src/banks/bank_12.asm"
    include "src/banks/bank_13.asm"
    include "src/banks/bank_14.asm"
    include "src/banks/bank_15.asm"
    include "src/banks/bank_16.asm"
    include "src/banks/bank_17.asm"
    include "src/banks/bank_18.asm"
    include "src/banks/bank_19.asm"
    include "src/banks/bank_1A.asm"
    include "src/banks/bank_1B.asm"
    include "src/banks/bank_1C.asm"
    include "src/banks/bank_1D.asm"
    include "src/banks/bank_1E.asm"
    include "src/banks/bank_1F.asm"